[package]
name = "straight-utils-module"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
crossbeam-channel = "0.5.15"
emacs = "0.19.0"
git2 = "0.20.2"
num_cpus = "1.17.0"
rayon = "1.11.0"
